/* tslint:disable */
/* eslint-disable */
/**
 * Suada API
 * OpenAPI specification for the Suada API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompletionMessagesInner
 */
export interface CompletionMessagesInner {
    /**
     * The role of the message\'s author.
     * @type {string}
     * @memberof CompletionMessagesInner
     */
    'role'?: CompletionMessagesInnerRoleEnum;
    /**
     * The contents of the message.
     * @type {string}
     * @memberof CompletionMessagesInner
     */
    'content'?: string;
    /**
     * An optional name for the participant. Provides the model information to differentiate between participants of the same role.
     * @type {string}
     * @memberof CompletionMessagesInner
     */
    'name'?: string | null;
}

export const CompletionMessagesInnerRoleEnum = {
    System: 'system',
    Assistant: 'assistant',
    User: 'user'
} as const;

export type CompletionMessagesInnerRoleEnum = typeof CompletionMessagesInnerRoleEnum[keyof typeof CompletionMessagesInnerRoleEnum];


