/* tslint:disable */
/* eslint-disable */
/**
 * Suada API
 * OpenAPI specification for the Suada API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompletionMessagesInner
 */
export interface CompletionMessagesInner {
    /**
     * The role of the message's author.
     * @type {string}
     * @memberof CompletionMessagesInner
     */
    role?: CompletionMessagesInnerRoleEnum;
    /**
     * The contents of the message.
     * @type {string}
     * @memberof CompletionMessagesInner
     */
    content?: string;
    /**
     * An optional name for the participant. Provides the model information to differentiate between participants of the same role.
     * @type {string}
     * @memberof CompletionMessagesInner
     */
    name?: string | null;
}


/**
 * @export
 */
export const CompletionMessagesInnerRoleEnum = {
    System: 'system',
    Assistant: 'assistant',
    User: 'user'
} as const;
export type CompletionMessagesInnerRoleEnum = typeof CompletionMessagesInnerRoleEnum[keyof typeof CompletionMessagesInnerRoleEnum];


/**
 * Check if a given object implements the CompletionMessagesInner interface.
 */
export function instanceOfCompletionMessagesInner(value: object): value is CompletionMessagesInner {
    return true;
}

export function CompletionMessagesInnerFromJSON(json: any): CompletionMessagesInner {
    return CompletionMessagesInnerFromJSONTyped(json, false);
}

export function CompletionMessagesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompletionMessagesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'] == null ? undefined : json['role'],
        'content': json['content'] == null ? undefined : json['content'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CompletionMessagesInnerToJSON(value?: CompletionMessagesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'role': value['role'],
        'content': value['content'],
        'name': value['name'],
    };
}

