/* tslint:disable */
/* eslint-disable */
/**
 * Suada API
 * OpenAPI specification for the Suada API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompletionResultUsage } from './CompletionResultUsage';
import {
    CompletionResultUsageFromJSON,
    CompletionResultUsageFromJSONTyped,
    CompletionResultUsageToJSON,
} from './CompletionResultUsage';
import type { CompletionResultChoicesInner } from './CompletionResultChoicesInner';
import {
    CompletionResultChoicesInnerFromJSON,
    CompletionResultChoicesInnerFromJSONTyped,
    CompletionResultChoicesInnerToJSON,
} from './CompletionResultChoicesInner';

/**
 * 
 * @export
 * @interface CompletionResult
 */
export interface CompletionResult {
    /**
     * 
     * @type {string}
     * @memberof CompletionResult
     */
    Id?: string;
    /**
     * 
     * @type {string}
     * @memberof CompletionResult
     */
    Object?: string;
    /**
     * 
     * @type {number}
     * @memberof CompletionResult
     */
    Created?: number;
    /**
     * 
     * @type {string}
     * @memberof CompletionResult
     */
    Model?: string;
    /**
     * 
     * @type {string}
     * @memberof CompletionResult
     */
    SystemFingerprint?: string;
    /**
     * 
     * @type {Array<CompletionResultChoicesInner>}
     * @memberof CompletionResult
     */
    Choices?: Array<CompletionResultChoicesInner>;
    /**
     * 
     * @type {CompletionResultUsage}
     * @memberof CompletionResult
     */
    Usage?: CompletionResultUsage;
}

/**
 * Check if a given object implements the CompletionResult interface.
 */
export function instanceOfCompletionResult(value: object): value is CompletionResult {
    return true;
}

export function CompletionResultFromJSON(json: any): CompletionResult {
    return CompletionResultFromJSONTyped(json, false);
}

export function CompletionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompletionResult {
    if (json == null) {
        return json;
    }
    return {
        
        'Id': json['id'] == null ? undefined : json['id'],
        'Object': json['object'] == null ? undefined : json['object'],
        'Created': json['created'] == null ? undefined : json['created'],
        'Model': json['model'] == null ? undefined : json['model'],
        'SystemFingerprint': json['system_fingerprint'] == null ? undefined : json['system_fingerprint'],
        'Choices': json['choices'] == null ? undefined : ((json['choices'] as Array<any>).map(CompletionResultChoicesInnerFromJSON)),
        'Usage': json['usage'] == null ? undefined : CompletionResultUsageFromJSON(json['usage']),
    };
}

export function CompletionResultToJSON(value?: CompletionResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['Id'],
        'object': value['Object'],
        'created': value['Created'],
        'model': value['Model'],
        'system_fingerprint': value['SystemFingerprint'],
        'choices': value['Choices'] == null ? undefined : ((value['Choices'] as Array<any>).map(CompletionResultChoicesInnerToJSON)),
        'usage': CompletionResultUsageToJSON(value['Usage']),
    };
}

