/* tslint:disable */
/* eslint-disable */
/**
 * Suada API
 * OpenAPI specification for the Suada API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompletionResultChoicesInnerMessage } from './CompletionResultChoicesInnerMessage';
import {
    CompletionResultChoicesInnerMessageFromJSON,
    CompletionResultChoicesInnerMessageFromJSONTyped,
    CompletionResultChoicesInnerMessageToJSON,
} from './CompletionResultChoicesInnerMessage';

/**
 * 
 * @export
 * @interface CompletionResultChoicesInner
 */
export interface CompletionResultChoicesInner {
    /**
     * 
     * @type {number}
     * @memberof CompletionResultChoicesInner
     */
    index?: number;
    /**
     * 
     * @type {CompletionResultChoicesInnerMessage}
     * @memberof CompletionResultChoicesInner
     */
    message?: CompletionResultChoicesInnerMessage;
    /**
     * 
     * @type {any}
     * @memberof CompletionResultChoicesInner
     */
    logprobs?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CompletionResultChoicesInner
     */
    finishReason?: string;
}

/**
 * Check if a given object implements the CompletionResultChoicesInner interface.
 */
export function instanceOfCompletionResultChoicesInner(value: object): value is CompletionResultChoicesInner {
    return true;
}

export function CompletionResultChoicesInnerFromJSON(json: any): CompletionResultChoicesInner {
    return CompletionResultChoicesInnerFromJSONTyped(json, false);
}

export function CompletionResultChoicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompletionResultChoicesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'message': json['message'] == null ? undefined : CompletionResultChoicesInnerMessageFromJSON(json['message']),
        'logprobs': json['logprobs'] == null ? undefined : json['logprobs'],
        'finishReason': json['finish_reason'] == null ? undefined : json['finish_reason'],
    };
}

export function CompletionResultChoicesInnerToJSON(value?: CompletionResultChoicesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'index': value['index'],
        'message': CompletionResultChoicesInnerMessageToJSON(value['message']),
        'logprobs': value['logprobs'],
        'finish_reason': value['finishReason'],
    };
}

