/* tslint:disable */
/* eslint-disable */
/**
 * Suada API
 * OpenAPI specification for the Suada API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompletionResultUsage
 */
export interface CompletionResultUsage {
    /**
     * 
     * @type {number}
     * @memberof CompletionResultUsage
     */
    prompt_tokens?: number;
    /**
     * 
     * @type {number}
     * @memberof CompletionResultUsage
     */
    completion_tokens?: number;
    /**
     * 
     * @type {number}
     * @memberof CompletionResultUsage
     */
    total_tokens?: number;
}

/**
 * Check if a given object implements the CompletionResultUsage interface.
 */
export function instanceOfCompletionResultUsage(value: object): value is CompletionResultUsage {
    return true;
}

export function CompletionResultUsageFromJSON(json: any): CompletionResultUsage {
    return CompletionResultUsageFromJSONTyped(json, false);
}

export function CompletionResultUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompletionResultUsage {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt_tokens': json['prompt_tokens'] == null ? undefined : json['prompt_tokens'],
        'completion_tokens': json['completion_tokens'] == null ? undefined : json['completion_tokens'],
        'total_tokens': json['total_tokens'] == null ? undefined : json['total_tokens'],
    };
}

export function CompletionResultUsageToJSON(value?: CompletionResultUsage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'prompt_tokens': value['prompt_tokens'],
        'completion_tokens': value['completion_tokens'],
        'total_tokens': value['total_tokens'],
    };
}

