/* tslint:disable */
/* eslint-disable */
/**
 * Suada API
 * OpenAPI specification for the Suada API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompletionResultChoicesInnerMessage
 */
export interface CompletionResultChoicesInnerMessage {
    /**
     * 
     * @type {string}
     * @memberof CompletionResultChoicesInnerMessage
     */
    Role?: string;
    /**
     * 
     * @type {string}
     * @memberof CompletionResultChoicesInnerMessage
     */
    Content?: string;
}

/**
 * Check if a given object implements the CompletionResultChoicesInnerMessage interface.
 */
export function instanceOfCompletionResultChoicesInnerMessage(value: object): value is CompletionResultChoicesInnerMessage {
    return true;
}

export function CompletionResultChoicesInnerMessageFromJSON(json: any): CompletionResultChoicesInnerMessage {
    return CompletionResultChoicesInnerMessageFromJSONTyped(json, false);
}

export function CompletionResultChoicesInnerMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompletionResultChoicesInnerMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'Role': json['role'] == null ? undefined : json['role'],
        'Content': json['content'] == null ? undefined : json['content'],
    };
}

export function CompletionResultChoicesInnerMessageToJSON(value?: CompletionResultChoicesInnerMessage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'role': value['Role'],
        'content': value['Content'],
    };
}

