name: Build for npm

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Fetch all tags
      - name: Fetch all tags
        run: git fetch --tags
      
      # Verify that the latest tag matches the given regex
      - name: Check for matching tag
        id: check_tag
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          
          # Define the regex pattern
          pattern='^v*.*.*-rc**'
          
          if [[ "$latest_tag" =~ $pattern ]]; then
            echo "Tag matches pattern: $latest_tag"
            echo "::set-output name=tag::$latest_tag"
          else
            echo "Tag does not match the pattern."
            exit 1  # Fail the job if the tag doesn't match
          fi

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # You can change this to the version you're using
          registry-url: 'https://registry.npmjs.org/'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the package (optional - only if your package needs to be built before publishing)
      - name: Build package
        run: npm run build