name: Build for npm

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Fetch all tags
      - name: Fetch all tags
        run: git fetch --tags
      
      # Verify that the latest tag matches the given regex
      - name: Check for matching tag
        id: check_tag
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          
          # Define the regex pattern
          pattern='^v\[[0-9]+\]\.\[[0-9]+\]\.\[[0-9]+\]\.-rc\[[0-9]+\]\[[0-9]+\]$'
          
          if [[ "$latest_tag" =~ $pattern ]]; then
            echo "Tag matches pattern: $latest_tag"
            echo "::set-output name=tag::$latest_tag"
          else
            echo "Tag does not match the pattern."
            exit 1  # Fail the job if the tag doesn't match
          fi

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # You can change this to the version you're using
          registry-url: 'https://registry.npmjs.org/'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the package (optional - only if your package needs to be built before publishing)
      - name: Build package
        run: npm run build

      # Publish to npm
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Optional: Create GitHub release
      - name: Create a Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          tag_name: ${{ github.ref }}
          title: Release ${{ github.ref_name }}
          prerelease: false
          automatic_release_tag: ${{ github.ref_name }}