name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the action only when a tag with semantic versioning format is pushed

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      deployments: write
      discussions: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # You can change this to the version you're using
          registry-url: 'https://registry.npmjs.org/'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the package (optional - only if your package needs to be built before publishing)
      - name: Build package
        run: npm run build

      # Publish to npm
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Optional: Create GitHub release
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false